In [1]:
import napari
import scipy as sp
import numpy as np
import tifffile
import scipy.ndimage as ndi
from skimage.feature import peak_local_max
import os
import glob
import cv2
import skimage as ski
import dask
import plotly.express as px
import pandas as pd
import plotly.graph_objs as go

This is similar to the analysis done for Sid/Ayantika's paper, however the thresholding algorithm used to find the two FISH signals worked quite poorly (they were in a hurry so I did not have much choice), and was regularly throwing away lots of images.  Sid decided to just go ahead and draw ROIs around what he thought was the bright and dim areas, which I will then use to figure out the closest CenpA pair as before.

# Setup Notebook

In [2]:
viewer = napari.Viewer()

In [3]:
# Choose the channel to find CenpA peaks in
peak_channel = 1

In [4]:
scale = [0.10, 0.031, 0.031]

# Utility Functions

In [5]:
def backsub(inp, radius=20):
    filterSize =(radius, radius)
    kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE,
                                    filterSize)
    blurred = cv2.GaussianBlur(inp, (5, 5), 0)
    tophat_img = cv2.morphologyEx(blurred,
                                cv2.MORPH_TOPHAT,
                                kernel)
    rtn = inp.astype(np.single) - (blurred-tophat_img)
    rtn = np.clip(rtn, 0, np.inf)
    return rtn
def backsub_3d(inp, radius=20):
    shape = inp.shape
    reshaped = inp.reshape(-1, shape[-2], shape[-1])
    process = [dask.delayed(backsub)(i, radius) for i in reshaped]
    rslt = np.array(dask.compute(*process))
    rslt = rslt.reshape(shape)
    return rslt

In [6]:
def filter_label_size(labels, min_size=10, max_size=100):
    from skimage import measure
    label_sizes = np.bincount(labels.ravel())
    too_small = label_sizes < min_size
    too_large = label_sizes > max_size
    labels[np.isin(labels, np.where(too_small | too_large))] = 0
    labels = ski.segmentation.relabel_sequential(labels)[0]
    return labels

In [7]:
def find_peaks(img, threshold=0.1, display=False):
    #LoG = -ndi.gaussian_laplace(img/1000, sigma=[2,4,4])
    #LoG = -ndi.gaussian_laplace(img/1000, sigma=[1,2,2])
    
    img = ski.transform.rescale(img, [0.5,1,1], order=1, preserve_range=True)
    LoG = -ndi.gaussian_laplace(img/1000, sigma=[2,2,2])
    max_peaks = peak_local_max(LoG, min_distance=1, threshold_rel=threshold)
    if display:
        viewer.add_image(LoG, blending='additive', colormap='magenta', scale=scale)
        viewer.add_points(max_peaks, n_dimensional=True, size=6, scale=scale, name='AllPeaks')
    return max_peaks

def pair_finder(peaks, max_dist=6, scale=[0.12, 0.04, 0.04]):
    scaled_peaks = peaks.copy().astype(float)
    scaled_peaks[:,0] = scaled_peaks[:,0] * scale[0]
    scaled_peaks[:,1] = scaled_peaks[:,1] * scale[1]
    scaled_peaks[:,2] = scaled_peaks[:,2] * scale[2]
    
    d_matrix = sp.spatial.distance.squareform(sp.spatial.distance.pdist(scaled_peaks))
    d_matrix[d_matrix==0] = 10000
    
    min_pos = np.argmin(d_matrix, axis=0)
    distances = np.min(d_matrix, axis=0)
    sorte = np.argsort(distances)
    
    return_distances = []
    lst = []
    for a in np.arange(0,len(sorte)):
        if distances[sorte[a]]<max_dist:
            if any([all (peaks[sorte[a]]==b) for b in lst]) | any([all(peaks[min_pos][sorte[a]]==b) for b in lst]):
                lst
            elif np.abs(peaks[sorte[a]][0]-peaks[min_pos][sorte[a]][0])>6:
                lst
            else:
                lst.append(peaks[sorte[a]])
                lst.append(peaks[min_pos][sorte[a]])
                return_distances.append(distances[sorte[a]])
    return lst, return_distances

def find_peaks_in_file(fname, display=False, threshold=0.16, viewer=None):
    img = tifffile.imread(fname)
    print(img.shape)
    peaks = find_peaks(img[:,peak_channel,:,:], threshold=threshold, display=display)
    filtered_peaks, distances = pair_finder(peaks, max_dist=1.2, scale=scale)
    
    if display:
        viewer.add_image(img, channel_axis=1, scale=scale)
        viewer.add_points(filtered_peaks[::2], n_dimensional=True, size=6, scale=scale, name='FilteredPeaks', face_color='magenta')
        viewer.add_points(filtered_peaks[1::2], n_dimensional=True, size=6, scale=scale, name='FilteredPeaks', face_color='yellow')
    return filtered_peaks, distances

In [8]:
def get_intensity_df(int_img, labels):
    df = pd.DataFrame(ski.measure.regionprops_table(labels, intensity_image=int_img, properties=['label', 'mean_intensity', 'area']))
    df['total_intensity'] = df['mean_intensity'] * df['area']
    return df.drop(columns=['area'])

def get_props_df(labels):
    df = pd.DataFrame(ski.measure.regionprops_table(labels, properties=['label', 'centroid', 'area']))
    return df

def get_all_props(int_img, labels):
    props_df = get_props_df(labels)
    c0_df = get_intensity_df(int_img[0], labels)
    c1_df = get_intensity_df(int_img[1], labels)
    c2_df = get_intensity_df(int_img[2], labels)
    c3_df = get_intensity_df(int_img[3], labels)
    all_df = props_df.merge(c0_df, on='label', suffixes=('', '_c0'))
    all_df = all_df.merge(c1_df, on='label', suffixes=('', '_c1'))
    all_df = all_df.merge(c2_df, on='label', suffixes=('', '_c2'))
    all_df = all_df.merge(c3_df, on='label', suffixes=('', '_c3'))
    return all_df

In [9]:
from roifile import ImagejRoi

def get_roi_mask(raw_fname):
    tail = os.path.split(raw_fname)[-1]
    fname = raw_fname.replace(tail, 'SUM_' + tail + 'f')
    if os.path.exists(fname)==False:
        fname = fname[0:-1]
        roi_file = fname.replace('.tif', '_ROI.zip')
    else:
        roi_file = fname.replace('.tiff', '_ROI.zip')

    img = ski.io.imread(fname)
    
    if os.path.exists(roi_file)==False:
        return img * 0
    rois = ImagejRoi.fromfile(roi_file)
    img_shape = img.shape[0:2]

    mask = np.zeros(img_shape)
    for idx, roi in enumerate(rois):
        init = np.array([roi.top, roi.left])
        if roi.multi_coordinates is not None:
            print('Bad')
            return mask
        pts = roi.integer_coordinates[:,::-1] + init[np.newaxis, :]
        mask = cv2.fillPoly(mask, [pts[:,::-1]], 2-idx) # He did dim first, I think the rest of the code assumes bright was first
    return mask.astype(int)

In [17]:
def get_mask(peak, img_shape, radius=8):
    blank_img = np.zeros(img_shape)
    cv2.line(blank_img, tuple(peak[0].astype(int)[::-1]), tuple(peak[1].astype(int)[::-1]), color=255, thickness=2)
    edt = ndi.distance_transform_edt(blank_img==0)
    binary = edt < radius
    return binary

def process_file(fname, viewer=None, display=False, max_distance=20):

    # Get peak pairs and distances
    peaks, distances = find_peaks_in_file(fname, display=display, viewer=viewer, threshold=0.16)
    pks_grouped = np.reshape(peaks, (-1, 2, 3))
    centers = np.mean(pks_grouped, axis=1)[:,1:3]
    if len(centers) < 4:
        print(f"Not enough peaks found in {fname}. Skipping file.")
        return pd.DataFrame()

    img = ski.io.imread(fname)
    img = np.moveaxis(img, -1, 0)
    img = backsub_3d(img, radius=20)

    # Get the 2 objects Sid selected
    fimg = img[0,:,:,:]
    pimg = fimg.sum(axis=0)[:,:]
    labels = get_roi_mask(fname)
    if np.max(labels) < 2:
        print(f"Not enough ROIs found in {fname}. Skipping file.")
        return pd.DataFrame()

    df = pd.DataFrame(ski.measure.regionprops_table(labels, intensity_image=pimg, properties=['label', 'area', 'centroid', 'mean_intensity']))
    df['total_intensity'] = df['mean_intensity'] * df['area']
    # Sort or trust him?
    df = df.rename(columns={'centroid-0': 'y', 'centroid-1': 'x'})
    #df = df.sort_values(by='total_intensity', ascending=False).rename(columns={'centroid-0': 'y', 'centroid-1': 'x'})

    # Get the bright and dim centroids from the FISH channel, calculate distances to all pairs' centers
    bright = df.iloc[0][['y','x']].values
    dim = df.iloc[1][['y','x']].values
    bright_distances = np.linalg.norm(centers - bright, axis=1)
    dim_distances = np.linalg.norm(centers - dim, axis=1)

    # Find the closest peak to the bright and dim FISH spots and their distances
    bright_peak = pks_grouped[np.argmin(bright_distances)][:,1:3]
    dim_peak = pks_grouped[np.argmin(dim_distances)][:,1:3]
    bright_peak_distance = bright_distances[np.argmin(bright_distances)]
    dim_peak_distance = dim_distances[np.argmin(dim_distances)]
    if bright_peak_distance > max_distance or dim_peak_distance > max_distance:
        print(f"Bright peak distance {bright_peak_distance} or dim peak distance {dim_peak_distance} exceeds max distance {max_distance}.")
        return pd.DataFrame()

    # Draw line connecting the 2 bright peaks and make a mask, and another for the dim peaks
    bright_mask = get_mask([bright_peak[0], bright_peak[1]], pimg.shape)
    dim_mask = get_mask([dim_peak[0], dim_peak[1]], pimg.shape)
    both_labels = bright_mask + dim_mask * 2

    # Get the intensity information for all channels
    proj_img = img.sum(axis=1)
    prop_df = get_all_props(proj_img, both_labels)

    if display:
        viewer.add_image(proj_img, scale=scale[1:], channel_axis=0)
        viewer.add_labels(labels, name='FISH Labels', scale=scale[1:])
        viewer.add_labels(both_labels, name='Areas', scale=scale[1:])
        viewer.layers[-1].contour = 2
    
    prop_df['FISH_area'] = df['area'].iloc[0:2].values
    prop_df['FISH_total_intensity'] = df['total_intensity'].iloc[0:2].values
    prop_df['FISH_mean_intensity'] = df['mean_intensity'].iloc[0:2].values
    prop_df['distance'] = np.array([bright_peak_distance, dim_peak_distance])
    prop_df['slices'] = img.shape[1]
    
    return prop_df

# Process Data

In [18]:
#fnames = glob.glob('*INCENP*/crop_rep*/*.tif')
fnames = glob.glob('CEN7/*/crop*/*.tif')
fname = fnames[0]
fnames

['CEN7\\Cen7_AuroraB_CENPA\\crop_rep1\\rep1_image001-1.tif',
 'CEN7\\Cen7_AuroraB_CENPA\\crop_rep1\\rep1_image003-1.tif',
 'CEN7\\Cen7_AuroraB_CENPA\\crop_rep1\\rep1_image003-2.tif',
 'CEN7\\Cen7_AuroraB_CENPA\\crop_rep1\\rep1_image004-1.tif',
 'CEN7\\Cen7_AuroraB_CENPA\\crop_rep1\\rep1_image005-1.tif',
 'CEN7\\Cen7_AuroraB_CENPA\\crop_rep1\\rep1_image005-2.tif',
 'CEN7\\Cen7_AuroraB_CENPA\\crop_rep1\\rep1_image005-3.tif',
 'CEN7\\Cen7_AuroraB_CENPA\\crop_rep1\\rep1_image006-1.tif',
 'CEN7\\Cen7_AuroraB_CENPA\\crop_rep1\\rep1_image006-2.tif',
 'CEN7\\Cen7_AuroraB_CENPA\\crop_rep1\\rep1_image007-1.tif',
 'CEN7\\Cen7_AuroraB_CENPA\\crop_rep1\\rep1_image008-1.tif',
 'CEN7\\Cen7_AuroraB_CENPA\\crop_rep1\\rep1_image009-1.tif',
 'CEN7\\Cen7_AuroraB_CENPA\\crop_rep1\\rep1_image010-1.tif',
 'CEN7\\Cen7_AuroraB_CENPA\\crop_rep1\\rep1_image013-1.tif',
 'CEN7\\Cen7_AuroraB_CENPA\\crop_rep1\\rep1_image013-2.tif',
 'CEN7\\Cen7_AuroraB_CENPA\\crop_rep1\\rep1_image015-1.tif',
 'CEN7\\Cen7_AuroraB_CENPA\\crop_rep2\\rep2_image001-1.tif',
 'CEN7\\Cen7_AuroraB_CENPA\\crop_rep2\\rep2_image002-1.tif',
 'CEN7\\Cen7_AuroraB_CENPA\\crop_rep2\\rep2_image002-2.tif',
 'CEN7\\Cen7_AuroraB_CENPA\\crop_rep2\\rep2_image004-1.tif',
 'CEN7\\Cen7_AuroraB_CENPA\\crop_rep2\\rep2_image005-1.tif',
 'CEN7\\Cen7_AuroraB_CENPA\\crop_rep2\\rep2_image006-1.tif',
 'CEN7\\Cen7_AuroraB_CENPA\\crop_rep2\\rep2_image007-1.tif',
 'CEN7\\Cen7_AuroraB_CENPA\\crop_rep2\\rep2_image008-1.tif',
 'CEN7\\Cen7_AuroraB_CENPA\\crop_rep2\\rep2_image010-1.tif',
 'CEN7\\Cen7_AuroraB_CENPA\\crop_rep2\\rep2_image010-2.tif',
 'CEN7\\Cen7_AuroraB_CENPA\\crop_rep2\\rep2_image012-1.tif',
 'CEN7\\Cen7_AuroraB_CENPA\\crop_rep2\\rep2_image013-1.tif',
 'CEN7\\Cen7_AuroraB_CENPA\\crop_rep2\\rep2_image015-1.tif',
 'CEN7\\Cen7_AuroraB_CENPA\\crop_rep2\\rep2_image016-1.tif',
 'CEN7\\Cen7_AuroraB_CENPA\\crop_rep2\\rep2_image016-2.tif',
 'CEN7\\Cen7_AuroraB_CENPA\\crop_rep2\\rep2_image017-1.tif',
 'CEN7\\Cen7_AuroraB_CENPA\\crop_rep2\\rep2_image018-1.tif',
 'CEN7\\Cen7_AuroraB_CENPA\\crop_rep2\\rep2_image019-1.tif',
 'CEN7\\Cen7_AuroraB_CENPA\\crop_rep2\\rep2_image020-1.tif',
 'CEN7\\Cen7_AuroraB_CENPA\\crop_rep3_left\\rep3_image001-1.tif',
 'CEN7\\Cen7_AuroraB_CENPA\\crop_rep3_left\\rep3_image001_rep2-1.tif',
 'CEN7\\Cen7_AuroraB_CENPA\\crop_rep3_left\\rep3_image001_rep2-2.tif',
 'CEN7\\Cen7_AuroraB_CENPA\\crop_rep3_left\\rep3_image002-1.tif',
 'CEN7\\Cen7_AuroraB_CENPA\\crop_rep3_left\\rep3_image002-2.tif',
 'CEN7\\Cen7_AuroraB_CENPA\\crop_rep3_left\\rep3_image002_rep2-1.tif',
 'CEN7\\Cen7_AuroraB_CENPA\\crop_rep3_left\\rep3_image003-1.tif',
 'CEN7\\Cen7_AuroraB_CENPA\\crop_rep3_left\\rep3_image003_rep2-1.tif',
 'CEN7\\Cen7_AuroraB_CENPA\\crop_rep3_left\\rep3_image003_rep2-2.tif',
 'CEN7\\Cen7_AuroraB_CENPA\\crop_rep3_left\\rep3_image004_rep2-1.tif',
 'CEN7\\Cen7_AuroraB_CENPA\\crop_rep3_left\\rep3_image005-1.tif',
 'CEN7\\Cen7_AuroraB_CENPA\\crop_rep3_left\\rep3_image005-2.tif',
 'CEN7\\Cen7_AuroraB_CENPA\\crop_rep3_left\\rep3_image005_rep2-1.tif',
 'CEN7\\Cen7_AuroraB_CENPA\\crop_rep3_left\\rep3_image006-1.tif',
 'CEN7\\Cen7_AuroraB_CENPA\\crop_rep3_left\\rep3_image006_rep2-1.tif',
 'CEN7\\Cen7_AuroraB_CENPA\\crop_rep3_left\\rep3_image007_rep2-1.tif',
 'CEN7\\Cen7_AuroraB_CENPA\\crop_rep3_left\\rep3_image008-1.tif',
 'CEN7\\Cen7_AuroraB_CENPA\\crop_rep3_left\\rep3_image008_rep2-1.tif',
 'CEN7\\Cen7_AuroraB_CENPA\\crop_rep3_left\\rep3_image009-1.tif',
 'CEN7\\Cen7_AuroraB_CENPA\\crop_rep3_left\\rep3_image009_rep2-1.tif',
 'CEN7\\Cen7_AuroraB_CENPA\\crop_rep3_left\\rep3_image010-1.tif',
 'CEN7\\Cen7_AuroraB_CENPA\\crop_rep3_left\\rep3_image010_rep2-1.tif',
 'CEN7\\Cen7_AuroraB_CENPA\\crop_rep3_left\\rep3_image011_rep2-1.tif',
 'CEN7\\Cen7_AuroraB_CENPA\\crop_rep3_left\\rep3_image012_rep2-1.tif',
 'CEN7\\Cen7_AuroraB_CENPA\\crop_rep3_left\\rep3_image013_rep2-1.tif',
 'CEN7\\Cen7_AuroraB_CENPA\\crop_rep3_left\\SUM_rep3_image001-1.tif',
 'CEN7\\Cen7_AuroraB_CENPA\\crop_rep3_left\\SUM_rep3_image001_rep2-1.tif',
 'CEN7\\Cen7_AuroraB_CENPA\\crop_rep3_left\\SUM_rep3_image001_rep2-2.tif',
 'CEN7\\Cen7_AuroraB_CENPA\\crop_rep3_left\\SUM_rep3_image002-1.tif',
 'CEN7\\Cen7_AuroraB_CENPA\\crop_rep3_left\\SUM_rep3_image002-2.tif',
 'CEN7\\Cen7_AuroraB_CENPA\\crop_rep3_left\\SUM_rep3_image002_rep2-1.tif',
 'CEN7\\Cen7_AuroraB_CENPA\\crop_rep3_left\\SUM_rep3_image003-1.tif',
 'CEN7\\Cen7_AuroraB_CENPA\\crop_rep3_left\\SUM_rep3_image003_rep2-1.tif',
 'CEN7\\Cen7_AuroraB_CENPA\\crop_rep3_left\\SUM_rep3_image003_rep2-2.tif',
 'CEN7\\Cen7_AuroraB_CENPA\\crop_rep3_left\\SUM_rep3_image004_rep2-1.tif',
 'CEN7\\Cen7_AuroraB_CENPA\\crop_rep3_left\\SUM_rep3_image005-1.tif',
 'CEN7\\Cen7_AuroraB_CENPA\\crop_rep3_left\\SUM_rep3_image005-2.tif',
 'CEN7\\Cen7_AuroraB_CENPA\\crop_rep3_left\\SUM_rep3_image005_rep2-1.tif',
 'CEN7\\Cen7_AuroraB_CENPA\\crop_rep3_left\\SUM_rep3_image006-1.tif',
 'CEN7\\Cen7_AuroraB_CENPA\\crop_rep3_left\\SUM_rep3_image006_rep2-1.tif',
 'CEN7\\Cen7_AuroraB_CENPA\\crop_rep3_left\\SUM_rep3_image007_rep2-1.tif',
 'CEN7\\Cen7_AuroraB_CENPA\\crop_rep3_left\\SUM_rep3_image008-1.tif',
 'CEN7\\Cen7_AuroraB_CENPA\\crop_rep3_left\\SUM_rep3_image008_rep2-1.tif',
 'CEN7\\Cen7_AuroraB_CENPA\\crop_rep3_left\\SUM_rep3_image009-1.tif',
 'CEN7\\Cen7_AuroraB_CENPA\\crop_rep3_left\\SUM_rep3_image009_rep2-1.tif',
 'CEN7\\Cen7_AuroraB_CENPA\\crop_rep3_left\\SUM_rep3_image010-1.tif',
 'CEN7\\Cen7_AuroraB_CENPA\\crop_rep3_left\\SUM_rep3_image010_rep2-1.tif',
 'CEN7\\Cen7_AuroraB_CENPA\\crop_rep3_left\\SUM_rep3_image011_rep2-1.tif',
 'CEN7\\Cen7_AuroraB_CENPA\\crop_rep3_left\\SUM_rep3_image012_rep2-1.tif',
 'CEN7\\Cen7_AuroraB_CENPA\\crop_rep3_left\\SUM_rep3_image013_rep2-1.tif',
 'CEN7\\Cen7_CENPB_CENPA\\crop_rep0\\sead012-1-1.tif',
 'CEN7\\Cen7_CENPB_CENPA\\crop_rep0\\spread001-1-1.tif',
 'CEN7\\Cen7_CENPB_CENPA\\crop_rep0\\spread002-1-1.tif',
 'CEN7\\Cen7_CENPB_CENPA\\crop_rep0\\spread003-1-1.tif',
 'CEN7\\Cen7_CENPB_CENPA\\crop_rep0\\spread004-1-1.tif',
 'CEN7\\Cen7_CENPB_CENPA\\crop_rep0\\spread005-1-1.tif',
 'CEN7\\Cen7_CENPB_CENPA\\crop_rep0\\spread006-1-1.tif',
 'CEN7\\Cen7_CENPB_CENPA\\crop_rep0\\spread006-2-1.tif',
 'CEN7\\Cen7_CENPB_CENPA\\crop_rep0\\spread007-1.tif',
 'CEN7\\Cen7_CENPB_CENPA\\crop_rep0\\spread008-1-1.tif',
 'CEN7\\Cen7_CENPB_CENPA\\crop_rep0\\spread009-1-1.tif',
 'CEN7\\Cen7_CENPB_CENPA\\crop_rep0\\spread009-2-1.tif',
 'CEN7\\Cen7_CENPB_CENPA\\crop_rep0\\spread011-1-1.tif',
 'CEN7\\Cen7_CENPB_CENPA\\crop_rep0\\spread013-1-1.tif',
 'CEN7\\Cen7_CENPB_CENPA\\crop_rep0\\spread013-2-1.tif',
 'CEN7\\Cen7_CENPB_CENPA\\crop_rep0\\spread014-1.tif',
 'CEN7\\Cen7_CENPB_CENPA\\crop_rep0\\spread014-2.tif',
 'CEN7\\Cen7_CENPB_CENPA\\crop_rep0\\spread014-3.tif',
 'CEN7\\Cen7_CENPB_CENPA\\crop_rep0\\spread015-1-1.tif',
 'CEN7\\Cen7_CENPB_CENPA\\crop_rep0\\spread015-2-1.tif',
 'CEN7\\Cen7_CENPB_CENPA\\crop_rep1\\image002-1.tif',
 'CEN7\\Cen7_CENPB_CENPA\\crop_rep1\\image003-1.tif',
 'CEN7\\Cen7_CENPB_CENPA\\crop_rep1\\image003-2.tif',
 'CEN7\\Cen7_CENPB_CENPA\\crop_rep1\\image004-1.tif',
 'CEN7\\Cen7_CENPB_CENPA\\crop_rep1\\image005-1.tif',
 'CEN7\\Cen7_CENPB_CENPA\\crop_rep1\\image005-2.tif',
 'CEN7\\Cen7_CENPB_CENPA\\crop_rep1\\image006-1.tif',
 'CEN7\\Cen7_CENPB_CENPA\\crop_rep1\\image007-1-1.tif',
 'CEN7\\Cen7_CENPB_CENPA\\crop_rep1\\image008-1.tif',
 'CEN7\\Cen7_CENPB_CENPA\\crop_rep1\\image008-2.tif',
 'CEN7\\Cen7_CENPB_CENPA\\crop_rep1\\image008-3.tif',
 'CEN7\\Cen7_CENPB_CENPA\\crop_rep1\\image009-1.tif',
 'CEN7\\Cen7_CENPB_CENPA\\crop_rep1\\image010-1.tif',
 'CEN7\\Cen7_CENPB_CENPA\\crop_rep1\\image010-2.tif',
 'CEN7\\Cen7_CENPB_CENPA\\crop_rep1\\image011-1.tif',
 'CEN7\\Cen7_CENPB_CENPA\\crop_rep1\\image011-2.tif',
 'CEN7\\Cen7_CENPB_CENPA\\crop_rep1\\image012-1.tif',
 'CEN7\\Cen7_CENPB_CENPA\\crop_rep1\\image012-2.tif',
 'CEN7\\Cen7_CENPB_CENPA\\crop_rep1\\image012-3.tif',
 'CEN7\\Cen7_CENPB_CENPA\\crop_rep1\\image013-1.tif',
 'CEN7\\Cen7_CENPB_CENPA\\crop_rep1\\image013-2.tif',
 'CEN7\\Cen7_CENPB_CENPA\\crop_rep2\\image001-1.tif',
 'CEN7\\Cen7_CENPB_CENPA\\crop_rep2\\image001-2.tif',
 'CEN7\\Cen7_CENPB_CENPA\\crop_rep2\\image002-1.tif',
 'CEN7\\Cen7_CENPB_CENPA\\crop_rep2\\image004-1.tif',
 'CEN7\\Cen7_CENPB_CENPA\\crop_rep2\\image005-1.tif',
 'CEN7\\Cen7_CENPB_CENPA\\crop_rep2\\image006-1.tif',
 'CEN7\\Cen7_CENPB_CENPA\\crop_rep2\\image007-1.tif',
 'CEN7\\Cen7_CENPB_CENPA\\crop_rep2\\image008-1.tif',
 'CEN7\\Cen7_CENPB_CENPA\\crop_rep2\\image009-1.tif',
 'CEN7\\Cen7_CENPB_CENPA\\crop_rep2\\image010-1.tif',
 'CEN7\\Cen7_CENPB_CENPA\\crop_rep2\\image010-2.tif',
 'CEN7\\Cen7_CENPB_CENPA\\crop_rep2\\image010-3.tif',
 'CEN7\\Cen7_CENPB_CENPA\\crop_rep3\\image001-1.tif',
 'CEN7\\Cen7_CENPB_CENPA\\crop_rep3\\image001-2.tif',
 'CEN7\\Cen7_CENPB_CENPA\\crop_rep3\\image002-1.tif',
 'CEN7\\Cen7_CENPB_CENPA\\crop_rep3\\image002-2.tif',
 'CEN7\\Cen7_CENPB_CENPA\\crop_rep3\\image003-1.tif',
 'CEN7\\Cen7_CENPB_CENPA\\crop_rep3\\image004-1.tif',
 'CEN7\\Cen7_CENPB_CENPA\\crop_rep3\\image005-1.tif',
 'CEN7\\Cen7_CENPB_CENPA\\crop_rep3\\image006-1.tif',
 'CEN7\\Cen7_CENPB_CENPA\\crop_rep3\\image007-1.tif',
 'CEN7\\Cen7_CENPB_CENPA\\crop_rep3\\image008-1.tif',
 'CEN7\\Cen7_CENPB_CENPA\\crop_rep3\\image008-2.tif',
 'CEN7\\Cen7_CENPB_CENPA\\crop_rep3\\image009-1.tif',
 'CEN7\\Cen7_CENPB_CENPA\\crop_rep3\\image010-1.tif',
 'CEN7\\Cen7_CENPE_CENPA\\crop_rep1\\rep1_image001-1.tif',
 'CEN7\\Cen7_CENPE_CENPA\\crop_rep1\\rep1_image002-1.tif',
 'CEN7\\Cen7_CENPE_CENPA\\crop_rep1\\rep1_image003-1.tif',
 'CEN7\\Cen7_CENPE_CENPA\\crop_rep1\\rep1_image004-1.tif',
 'CEN7\\Cen7_CENPE_CENPA\\crop_rep1\\rep1_image005-1.tif',
 'CEN7\\Cen7_CENPE_CENPA\\crop_rep1\\rep1_image006-1.tif',
 'CEN7\\Cen7_CENPE_CENPA\\crop_rep1\\rep1_image007-1.tif',
 'CEN7\\Cen7_CENPE_CENPA\\crop_rep1\\rep1_image008-1.tif',
 'CEN7\\Cen7_CENPE_CENPA\\crop_rep1\\rep1_image008-2.tif',
 'CEN7\\Cen7_CENPE_CENPA\\crop_rep1\\rep1_image009-1.tif',
 'CEN7\\Cen7_CENPE_CENPA\\crop_rep1\\rep1_image009-2.tif',
 'CEN7\\Cen7_CENPE_CENPA\\crop_rep1\\rep1_image010-1.tif',
 'CEN7\\Cen7_CENPE_CENPA\\crop_rep1\\rep1_image012-1.tif',
 'CEN7\\Cen7_CENPE_CENPA\\crop_rep1\\rep1_image014-1.tif',
 'CEN7\\Cen7_CENPE_CENPA\\crop_rep1\\rep1_image015-1.tif',
 'CEN7\\Cen7_CENPE_CENPA\\crop_rep1\\rep1_image016-1.tif',
 'CEN7\\Cen7_CENPE_CENPA\\crop_rep1\\rep1_image018-1.tif',
 'CEN7\\Cen7_CENPE_CENPA\\crop_rep2\\rep2_image006-1.tif',
 'CEN7\\Cen7_CENPE_CENPA\\crop_rep2\\rep2_image007-1.tif',
 'CEN7\\Cen7_CENPE_CENPA\\crop_rep2\\rep2_image008-1.tif',
 'CEN7\\Cen7_CENPE_CENPA\\crop_rep2\\rep2_image009-1.tif',
 'CEN7\\Cen7_CENPE_CENPA\\crop_rep2\\rep2_image010-1.tif',
 'CEN7\\Cen7_CENPE_CENPA\\crop_rep2\\rep2_image011-1.tif',
 'CEN7\\Cen7_CENPE_CENPA\\crop_rep2\\rep2_image012-1.tif',
 'CEN7\\Cen7_CENPE_CENPA\\crop_rep2\\rep2_image014-1.tif',
 'CEN7\\Cen7_CENPE_CENPA\\crop_rep2\\rep2_image015-1.tif',
 'CEN7\\Cen7_CENPE_CENPA\\crop_rep2\\rep2_image015-2.tif',
 'CEN7\\Cen7_CENPE_CENPA\\crop_rep2\\rep2_image016-1.tif',
 'CEN7\\Cen7_CENPE_CENPA\\crop_rep2\\rep2_image016-2.tif',
 'CEN7\\Cen7_CENPE_CENPA\\crop_rep2\\rep2_image017-1.tif',
 'CEN7\\Cen7_CENPE_CENPA\\crop_rep2\\rep2_image017-2.tif',
 'CEN7\\Cen7_CENPE_CENPA\\crop_rep2\\rep2_image018-1.tif',
 'CEN7\\Cen7_CENPE_CENPA\\crop_rep2\\rep2_image019-1.tif',
 'CEN7\\Cen7_CENPE_CENPA\\crop_rep2\\rep2_image019-2.tif',
 'CEN7\\Cen7_CENPE_CENPA\\crop_rep3\\rep3_image001-1.tif',
 'CEN7\\Cen7_CENPE_CENPA\\crop_rep3\\rep3_image001-2.tif',
 'CEN7\\Cen7_CENPE_CENPA\\crop_rep3\\rep3_image002-1.tif',
 'CEN7\\Cen7_CENPE_CENPA\\crop_rep3\\rep3_image003-1.tif',
 'CEN7\\Cen7_CENPE_CENPA\\crop_rep3\\rep3_image003-2.tif',
 'CEN7\\Cen7_CENPE_CENPA\\crop_rep3\\rep3_image003-3.tif',
 'CEN7\\Cen7_CENPE_CENPA\\crop_rep3\\rep3_image004-1.tif',
 'CEN7\\Cen7_CENPE_CENPA\\crop_rep3\\rep3_image004-2.tif',
 'CEN7\\Cen7_CENPE_CENPA\\crop_rep3\\rep3_image005-1.tif',
 'CEN7\\Cen7_CENPE_CENPA\\crop_rep3\\rep3_image005-2.tif',
 'CEN7\\Cen7_CENPE_CENPA\\crop_rep3\\rep3_image006-1.tif',
 'CEN7\\Cen7_CENPE_CENPA\\crop_rep3\\rep3_image008-1.tif',
 'CEN7\\Cen7_CENPE_CENPA\\crop_rep3\\rep3_image009-1.tif',
 'CEN7\\Cen7_CENPE_CENPA\\crop_rep3\\rep3_image009-2.tif',
 'CEN7\\Cen7_CENPE_CENPA\\crop_rep3\\rep3_image010-1.tif',
 'CEN7\\Cen7_CENPE_CENPA\\crop_rep3\\rep3_image011-2.tif',
 'CEN7\\Cen7_CENPE_CENPA\\crop_rep3\\rep3_image012-1.tif',
 'CEN7\\Cen7_CENPE_CENPA\\crop_rep3\\rep3_image013-1.tif',
 'CEN7\\Cen7_CENPE_CENPA\\crop_rep3\\rep3_image013-2.tif',
 'CEN7\\Cen7_CENPE_CENPA\\crop_rep3\\rep3_image014-1.tif',
 'CEN7\\Cen7_CENPE_CENPA\\crop_rep3\\rep3_image015-1.tif',
 'CEN7\\Cen7_CENPE_CENPA\\crop_rep3\\rep3_image017-1.tif',
 'CEN7\\Cen7_CENPE_CENPA\\crop_rep3\\rep3_image017-2.tif',
 'CEN7\\Cen7_INCENP_CENPA\\crop_rep2\\rep2_trep1_image001-1.tif',
 'CEN7\\Cen7_INCENP_CENPA\\crop_rep2\\rep2_trep1_image002-1.tif',
 'CEN7\\Cen7_INCENP_CENPA\\crop_rep2\\rep2_trep1_image002-2.tif',
 'CEN7\\Cen7_INCENP_CENPA\\crop_rep2\\rep2_trep1_image002-3.tif',
 'CEN7\\Cen7_INCENP_CENPA\\crop_rep2\\rep2_trep1_image003-1.tif',
 'CEN7\\Cen7_INCENP_CENPA\\crop_rep2\\rep2_trep1_image004-1.tif',
 'CEN7\\Cen7_INCENP_CENPA\\crop_rep2\\rep2_trep1_image004-2.tif',
 'CEN7\\Cen7_INCENP_CENPA\\crop_rep2\\rep2_trep1_image006-1.tif',
 'CEN7\\Cen7_INCENP_CENPA\\crop_rep2\\rep2_trep1_image008-1.tif',
 'CEN7\\Cen7_INCENP_CENPA\\crop_rep2\\rep2_trep1_image010-1.tif',
 'CEN7\\Cen7_INCENP_CENPA\\crop_rep2\\rep2_trep1_image011-1.tif',
 'CEN7\\Cen7_INCENP_CENPA\\crop_rep2\\rep2_trep1_image012-1.tif',
 'CEN7\\Cen7_INCENP_CENPA\\crop_rep5\\rep5_2_image_0002-1.tif',
 'CEN7\\Cen7_INCENP_CENPA\\crop_rep5\\rep5_2_image_0003-1.tif',
 'CEN7\\Cen7_INCENP_CENPA\\crop_rep5\\rep5_2_image_0007-1.tif',
 'CEN7\\Cen7_INCENP_CENPA\\crop_rep5\\rep5_2_image_0008-1.tif',
 'CEN7\\Cen7_INCENP_CENPA\\crop_rep5\\rep5_2_image_0011-1.tif',
 'CEN7\\Cen7_INCENP_CENPA\\crop_rep5\\rep5_2_image_0011-2.tif',
 'CEN7\\Cen7_INCENP_CENPA\\crop_rep5\\rep5_2_image_0012-1.tif',
 'CEN7\\Cen7_INCENP_CENPA\\crop_rep5\\rep5_2_image_0013-1.tif',
 'CEN7\\Cen7_INCENP_CENPA\\crop_rep5\\rep5_2_image_0014-1.tif',
 'CEN7\\Cen7_INCENP_CENPA\\crop_rep5\\rep5_2_image_016-1.tif',
 'CEN7\\Cen7_INCENP_CENPA\\crop_rep5\\rep5_2_image_016-2.tif',
 'CEN7\\Cen7_INCENP_CENPA\\crop_rep5\\rep5_2_image_017-1.tif',
 'CEN7\\Cen7_INCENP_CENPA\\crop_rep5\\rep5_image_002-1.tif',
 'CEN7\\Cen7_INCENP_CENPA\\crop_rep5\\rep5_image_004-1.tif',
 'CEN7\\Cen7_INCENP_CENPA\\crop_rep5\\rep5_image_007-1.tif',
 'CEN7\\Cen7_INCENP_CENPA\\crop_rep5\\rep5_image_010-1.tif',
 'CEN7\\Cen7_INCENP_CENPA\\crop_rep5\\rep5_image_015-1.tif',
 'CEN7\\Cen7_INCENP_CENPA\\crop_rep5\\rep5_image_024-1.tif',
 'CEN7\\Cen7_INCENP_CENPA\\crop_rep5\\rep5_image_027-1.tif',
 'CEN7\\Cen7_INCENP_CENPA\\crop_rep7_left\\rep7_image001-1.tif',
 'CEN7\\Cen7_INCENP_CENPA\\crop_rep7_left\\rep7_image002-1.tif',
 'CEN7\\Cen7_INCENP_CENPA\\crop_rep7_left\\rep7_image003-1.tif',
 'CEN7\\Cen7_INCENP_CENPA\\crop_rep7_left\\rep7_image004-1.tif',
 'CEN7\\Cen7_INCENP_CENPA\\crop_rep7_left\\rep7_image005-1.tif',
 'CEN7\\Cen7_INCENP_CENPA\\crop_rep7_left\\rep7_image006-1.tif',
 'CEN7\\Cen7_INCENP_CENPA\\crop_rep7_left\\rep7_image006-2.tif',
 'CEN7\\Cen7_INCENP_CENPA\\crop_rep7_left\\rep7_image007-1.tif',
 'CEN7\\Cen7_INCENP_CENPA\\crop_rep7_left\\rep7_image008-1.tif',
 'CEN7\\Cen7_INCENP_CENPA\\crop_rep7_left\\rep7_image009-1.tif',
 'CEN7\\Cen7_INCENP_CENPA\\crop_rep7_left\\rep7_image010-1.tif',
 'CEN7\\Cen7_INCENP_CENPA\\crop_rep7_left\\rep7_image011-1.tif',
 'CEN7\\Cen7_INCENP_CENPA\\crop_rep7_left\\rep7_image012-1.tif',
 'CEN7\\Cen7_INCENP_CENPA\\crop_rep7_left\\rep7_image013-1.tif',
 'CEN7\\Cen7_INCENP_CENPA\\crop_rep7_left\\rep7_image014-1.tif',
 'CEN7\\Cen7_INCENP_CENPA\\crop_rep7_left\\rep7_image015-1.tif',
 'CEN7\\Cen7_INCENP_CENPA\\crop_rep7_left\\rep7_image016-1.tif',
 'CEN7\\Cen7_INCENP_CENPA\\crop_rep7_left\\rep7_image018-1.tif',
 'CEN7\\Cen7_INCENP_CENPA\\crop_rep7_left\\rep7_image019-1.tif',
 'CEN7\\Cen7_INCENP_CENPA\\crop_rep7_left\\rep7_image019-2.tif',
 'CEN7\\Cen7_INCENP_CENPA\\crop_rep7_left\\rep7_image021-1.tif',
 'CEN7\\Cen7_INCENP_CENPA\\crop_rep7_left\\SUM_rep7_image001-1.tif',
 'CEN7\\Cen7_INCENP_CENPA\\crop_rep7_left\\SUM_rep7_image002-1.tif',
 'CEN7\\Cen7_INCENP_CENPA\\crop_rep7_left\\SUM_rep7_image003-1.tif',
 'CEN7\\Cen7_INCENP_CENPA\\crop_rep7_left\\SUM_rep7_image004-1.tif',
 'CEN7\\Cen7_INCENP_CENPA\\crop_rep7_left\\SUM_rep7_image005-1.tif',
 'CEN7\\Cen7_INCENP_CENPA\\crop_rep7_left\\SUM_rep7_image006-1.tif',
 'CEN7\\Cen7_INCENP_CENPA\\crop_rep7_left\\SUM_rep7_image006-2.tif',
 'CEN7\\Cen7_INCENP_CENPA\\crop_rep7_left\\SUM_rep7_image007-1.tif',
 'CEN7\\Cen7_INCENP_CENPA\\crop_rep7_left\\SUM_rep7_image008-1.tif',
 'CEN7\\Cen7_INCENP_CENPA\\crop_rep7_left\\SUM_rep7_image009-1.tif',
 'CEN7\\Cen7_INCENP_CENPA\\crop_rep7_left\\SUM_rep7_image010-1.tif',
 'CEN7\\Cen7_INCENP_CENPA\\crop_rep7_left\\SUM_rep7_image011-1.tif',
 'CEN7\\Cen7_INCENP_CENPA\\crop_rep7_left\\SUM_rep7_image012-1.tif',
 'CEN7\\Cen7_INCENP_CENPA\\crop_rep7_left\\SUM_rep7_image013-1.tif',
 'CEN7\\Cen7_INCENP_CENPA\\crop_rep7_left\\SUM_rep7_image014-1.tif',
 'CEN7\\Cen7_INCENP_CENPA\\crop_rep7_left\\SUM_rep7_image015-1.tif',
 'CEN7\\Cen7_INCENP_CENPA\\crop_rep7_left\\SUM_rep7_image016-1.tif',
 'CEN7\\Cen7_INCENP_CENPA\\crop_rep7_left\\SUM_rep7_image018-1.tif',
 'CEN7\\Cen7_INCENP_CENPA\\crop_rep7_left\\SUM_rep7_image019-1.tif',
 'CEN7\\Cen7_INCENP_CENPA\\crop_rep7_left\\SUM_rep7_image019-2.tif',
 'CEN7\\Cen7_INCENP_CENPA\\crop_rep7_left\\SUM_rep7_image021-1.tif',
 'CEN7\\Cen7_KNL1_CENPA\\crop_rep1\\rep1_image001-1.tif',
 'CEN7\\Cen7_KNL1_CENPA\\crop_rep1\\rep1_image002-1.tif',
 'CEN7\\Cen7_KNL1_CENPA\\crop_rep1\\rep1_image004-1.tif',
 'CEN7\\Cen7_KNL1_CENPA\\crop_rep1\\rep1_image006-1.tif',
 'CEN7\\Cen7_KNL1_CENPA\\crop_rep1\\rep1_image008-1.tif',
 'CEN7\\Cen7_KNL1_CENPA\\crop_rep1\\rep1_image009-1.tif',
 'CEN7\\Cen7_KNL1_CENPA\\crop_rep1\\rep1_image010-1.tif',
 'CEN7\\Cen7_KNL1_CENPA\\crop_rep1\\rep1_image012-1.tif',
 'CEN7\\Cen7_KNL1_CENPA\\crop_rep2\\cen7rep2_image1004-1.tif',
 'CEN7\\Cen7_KNL1_CENPA\\crop_rep2\\cen7rep2_image1004-2.tif',
 'CEN7\\Cen7_KNL1_CENPA\\crop_rep2\\cen7rep2_image1006-1.tif',
 'CEN7\\Cen7_KNL1_CENPA\\crop_rep2\\cen7rep2_image1007-1.tif',
 'CEN7\\Cen7_KNL1_CENPA\\crop_rep2\\cen7rep2_image1007-2.tif',
 'CEN7\\Cen7_KNL1_CENPA\\crop_rep2\\cen7rep2_image1008-1.tif',
 'CEN7\\Cen7_KNL1_CENPA\\crop_rep2\\cen7rep2_image1009-1.tif',
 'CEN7\\Cen7_KNL1_CENPA\\crop_rep2\\cen7rep2_image1010-1.tif',
 'CEN7\\Cen7_KNL1_CENPA\\crop_rep2\\cen7rep2_image1011-1.tif',
 'CEN7\\Cen7_KNL1_CENPA\\crop_rep2\\cen7rep2_image1012-1.tif',
 'CEN7\\Cen7_KNL1_CENPA\\crop_rep2\\cen7rep2_image1013-1.tif',
 'CEN7\\Cen7_KNL1_CENPA\\crop_rep2\\cen7rep2_image1015-1.tif',
 'CEN7\\Cen7_KNL1_CENPA\\crop_rep2\\cen7rep2_image1016-1.tif',
 'CEN7\\Cen7_KNL1_CENPA\\crop_rep2\\cen7rep2_image1017-1.tif',
 'CEN7\\Cen7_KNL1_CENPA\\crop_rep2\\cen7rep2_image1017-2.tif',
 'CEN7\\Cen7_KNL1_CENPA\\crop_rep2\\cen7rep2_image1019-1.tif',
 'CEN7\\Cen7_KNL1_CENPA\\crop_rep2\\cen7rep2_image1020-1.tif',
 'CEN7\\Cen7_KNL1_CENPA\\crop_rep2\\cen7rep2_image1021-1.tif',
 'CEN7\\Cen7_KNL1_CENPA\\crop_rep2\\rep1_image001-1.tif',
 'CEN7\\Cen7_KNL1_CENPA\\crop_rep2\\rep1_image002-1.tif',
 'CEN7\\Cen7_KNL1_CENPA\\crop_rep2\\rep1_image003-1.tif',
 'CEN7\\Cen7_KNL1_CENPA\\crop_rep2\\rep1_image004-1.tif',
 'CEN7\\Cen7_KNL1_CENPA\\crop_rep3\\rep3_2_image002-1.tif',
 'CEN7\\Cen7_KNL1_CENPA\\crop_rep3\\rep3_2_image002-2.tif',
 'CEN7\\Cen7_KNL1_CENPA\\crop_rep3\\rep3_2_image003-1.tif',
 'CEN7\\Cen7_KNL1_CENPA\\crop_rep3\\rep3_2_image003-2.tif',
 'CEN7\\Cen7_KNL1_CENPA\\crop_rep3\\rep3_2_image004-1.tif',
 'CEN7\\Cen7_KNL1_CENPA\\crop_rep3\\rep3_2_image005-1.tif',
 'CEN7\\Cen7_KNL1_CENPA\\crop_rep3\\rep3_2_image009-1.tif',
 'CEN7\\Cen7_KNL1_CENPA\\crop_rep3\\rep3_2_image012-1.tif',
 'CEN7\\Cen7_KNL1_CENPA\\crop_rep3\\rep3_2_image012-2.tif',
 'CEN7\\Cen7_KNL1_CENPA\\crop_rep3\\rep3_2_image013-1.tif',
 'CEN7\\Cen7_KNL1_CENPA\\crop_rep3\\rep3_image001-1.tif',

In [12]:
# View example to make sure everything works
process_file('CEN7/Cen7_CENPB_CENPA/crop_rep2/image008-1.tif', viewer=viewer, display=True)

(17, 4, 484, 554)
Bright peak distance 4.367743394488857 or dim peak distance 96.74877068298096 exceeds max distance 20.

Empty DataFrame
Columns: []
Index: []

In [19]:
df = pd.DataFrame()
for fname in fnames:
    print(fname)
    if 'SUM_' in fname:
        print("Skipping SUM file")
        continue
    prop_df = process_file(fname, viewer=viewer, display=False, max_distance=20)
    prop_df['filename'] = fname
    df = pd.concat([df, prop_df])

CEN7\Cen7_AuroraB_CENPA\crop_rep1\rep1_image001-1.tif
(33, 4, 353, 191)
CEN7\Cen7_AuroraB_CENPA\crop_rep1\rep1_image003-1.tif
(37, 4, 252, 243)
CEN7\Cen7_AuroraB_CENPA\crop_rep1\rep1_image003-2.tif
(37, 4, 208, 185)
CEN7\Cen7_AuroraB_CENPA\crop_rep1\rep1_image004-1.tif
(31, 4, 348, 412)
CEN7\Cen7_AuroraB_CENPA\crop_rep1\rep1_image005-1.tif
(31, 4, 481, 316)
CEN7\Cen7_AuroraB_CENPA\crop_rep1\rep1_image005-2.tif
(31, 4, 331, 279)
Bright peak distance 21.457276250051272 or dim peak distance 2.3038664139907707 exceeds max distance 20.
CEN7\Cen7_AuroraB_CENPA\crop_rep1\rep1_image005-3.tif
(31, 4, 268, 320)
CEN7\Cen7_AuroraB_CENPA\crop_rep1\rep1_image006-1.tif
(34, 4, 487, 261)
CEN7\Cen7_AuroraB_CENPA\crop_rep1\rep1_image006-2.tif
(34, 4, 126, 247)
Bright peak distance 6.029776172632075 or dim peak distance 29.07227064170779 exceeds max distance 20.
CEN7\Cen7_AuroraB_CENPA\crop_rep1\rep1_image007-1.tif
(29, 4, 312, 236)
CEN7\Cen7_AuroraB_CENPA\crop_rep1\rep1_image008-1.tif
(35, 4, 236, 222)
CEN7\Cen7_AuroraB_CENPA\crop_rep1\rep1_image009-1.tif
(37, 4, 686, 248)
CEN7\Cen7_AuroraB_CENPA\crop_rep1\rep1_image010-1.tif
(47, 4, 181, 170)
CEN7\Cen7_AuroraB_CENPA\crop_rep1\rep1_image013-1.tif
(37, 4, 311, 328)
CEN7\Cen7_AuroraB_CENPA\crop_rep1\rep1_image013-2.tif
(37, 4, 157, 268)
CEN7\Cen7_AuroraB_CENPA\crop_rep1\rep1_image015-1.tif
(30, 4, 202, 230)
CEN7\Cen7_AuroraB_CENPA\crop_rep2\rep2_image001-1.tif
(35, 4, 273, 266)
Bright peak distance 42.42811487216124 or dim peak distance 1.4632669958105038 exceeds max distance 20.
CEN7\Cen7_AuroraB_CENPA\crop_rep2\rep2_image002-1.tif
(27, 4, 291, 277)
CEN7\Cen7_AuroraB_CENPA\crop_rep2\rep2_image002-2.tif
(27, 4, 300, 223)
CEN7\Cen7_AuroraB_CENPA\crop_rep2\rep2_image004-1.tif
(27, 4, 227, 304)
CEN7\Cen7_AuroraB_CENPA\crop_rep2\rep2_image005-1.tif
(23, 4, 310, 316)
CEN7\Cen7_AuroraB_CENPA\crop_rep2\rep2_image006-1.tif
(31, 4, 235, 172)
CEN7\Cen7_AuroraB_CENPA\crop_rep2\rep2_image007-1.tif
(30, 4, 198, 290)
Not enough peaks found in CEN7\Cen7_AuroraB_CENPA\crop_rep2\rep2_image007-1.tif. Skipping file.
CEN7\Cen7_AuroraB_CENPA\crop_rep2\rep2_image008-1.tif
(28, 4, 466, 281)
CEN7\Cen7_AuroraB_CENPA\crop_rep2\rep2_image010-1.tif
(27, 4, 178, 482)
CEN7\Cen7_AuroraB_CENPA\crop_rep2\rep2_image010-2.tif
(27, 4, 222, 137)
CEN7\Cen7_AuroraB_CENPA\crop_rep2\rep2_image012-1.tif
(40, 4, 134, 199)
CEN7\Cen7_AuroraB_CENPA\crop_rep2\rep2_image013-1.tif
(30, 4, 266, 344)
CEN7\Cen7_AuroraB_CENPA\crop_rep2\rep2_image015-1.tif
(31, 4, 187, 232)
CEN7\Cen7_AuroraB_CENPA\crop_rep2\rep2_image016-1.tif
(37, 4, 186, 212)
CEN7\Cen7_AuroraB_CENPA\crop_rep2\rep2_image016-2.tif
(37, 4, 468, 169)
CEN7\Cen7_AuroraB_CENPA\crop_rep2\rep2_image017-1.tif
(31, 4, 141, 334)
CEN7\Cen7_AuroraB_CENPA\crop_rep2\rep2_image018-1.tif
(35, 4, 245, 364)
CEN7\Cen7_AuroraB_CENPA\crop_rep2\rep2_image019-1.tif
(25, 4, 336, 255)
CEN7\Cen7_AuroraB_CENPA\crop_rep2\rep2_image020-1.tif
(39, 4, 272, 554)
CEN7\Cen7_AuroraB_CENPA\crop_rep3_left\rep3_image001-1.tif
(46, 4, 491, 492)
Bright peak distance 0.2732832545824363 or dim peak distance 146.42847316615814 exceeds max distance 20.
CEN7\Cen7_AuroraB_CENPA\crop_rep3_left\rep3_image001_rep2-1.tif
(35, 4, 759, 813)
Not enough peaks found in CEN7\Cen7_AuroraB_CENPA\crop_rep3_left\rep3_image001_rep2-1.tif. Skipping file.
CEN7\Cen7_AuroraB_CENPA\crop_rep3_left\rep3_image001_rep2-2.tif
(35, 4, 423, 489)
CEN7\Cen7_AuroraB_CENPA\crop_rep3_left\rep3_image002-1.tif
(42, 4, 426, 546)
CEN7\Cen7_AuroraB_CENPA\crop_rep3_left\rep3_image002-2.tif
(42, 4, 426, 435)
CEN7\Cen7_AuroraB_CENPA\crop_rep3_left\rep3_image002_rep2-1.tif
(33, 4, 457, 280)
CEN7\Cen7_AuroraB_CENPA\crop_rep3_left\rep3_image003-1.tif
(37, 4, 537, 534)
CEN7\Cen7_AuroraB_CENPA\crop_rep3_left\rep3_image003_rep2-1.tif
(44, 4, 399, 324)
Bright peak distance 31.806237862647468 or dim peak distance 1.953307516469595 exceeds max distance 20.
CEN7\Cen7_AuroraB_CENPA\crop_rep3_left\rep3_image003_rep2-2.tif
(44, 4, 414, 405)
Bright peak distance 25.286672940104648 or dim peak distance 11.820658920537811 exceeds max distance 20.
CEN7\Cen7_AuroraB_CENPA\crop_rep3_left\rep3_image004_rep2-1.tif
(53, 4, 540, 468)
CEN7\Cen7_AuroraB_CENPA\crop_rep3_left\rep3_image005-1.tif
(35, 4, 552, 406)
CEN7\Cen7_AuroraB_CENPA\crop_rep3_left\rep3_image005-2.tif
(35, 4, 281, 404)
CEN7\Cen7_AuroraB_CENPA\crop_rep3_left\rep3_image005_rep2-1.tif
(37, 4, 330, 579)
CEN7\Cen7_AuroraB_CENPA\crop_rep3_left\rep3_image006-1.tif
(37, 4, 526, 506)
CEN7\Cen7_AuroraB_CENPA\crop_rep3_left\rep3_image006_rep2-1.tif
(64, 4, 243, 183)
CEN7\Cen7_AuroraB_CENPA\crop_rep3_left\rep3_image007_rep2-1.tif
(51, 4, 354, 318)
CEN7\Cen7_AuroraB_CENPA\crop_rep3_left\rep3_image008-1.tif
(32, 4, 352, 421)
CEN7\Cen7_AuroraB_CENPA\crop_rep3_left\rep3_image008_rep2-1.tif
(48, 4, 219, 480)
Bright peak distance 3.166729823931577 or dim peak distance 81.51691584192322 exceeds max distance 20.
CEN7\Cen7_AuroraB_CENPA\crop_rep3_left\rep3_image009-1.tif
(35, 4, 296, 367)
CEN7\Cen7_AuroraB_CENPA\crop_rep3_left\rep3_image009_rep2-1.tif
(44, 4, 531, 538)
CEN7\Cen7_AuroraB_CENPA\crop_rep3_left\rep3_image010-1.tif
(43, 4, 424, 757)
CEN7\Cen7_AuroraB_CENPA\crop_rep3_left\rep3_image010_rep2-1.tif
(43, 4, 273, 714)
CEN7\Cen7_AuroraB_CENPA\crop_rep3_left\rep3_image011_rep2-1.tif
(35, 4, 498, 441)
CEN7\Cen7_AuroraB_CENPA\crop_rep3_left\rep3_image012_rep2-1.tif
(34, 4, 360, 336)
CEN7\Cen7_AuroraB_CENPA\crop_rep3_left\rep3_image013_rep2-1.tif
(37, 4, 276, 272)
CEN7\Cen7_AuroraB_CENPA\crop_rep3_left\SUM_rep3_image001-1.tif
Skipping SUM file
CEN7\Cen7_AuroraB_CENPA\crop_rep3_left\SUM_rep3_image001_rep2-1.tif
Skipping SUM file
CEN7\Cen7_AuroraB_CENPA\crop_rep3_left\SUM_rep3_image001_rep2-2.tif
Skipping SUM file
CEN7\Cen7_AuroraB_CENPA\crop_rep3_left\SUM_rep3_image002-1.tif
Skipping SUM file
CEN7\Cen7_AuroraB_CENPA\crop_rep3_left\SUM_rep3_image002-2.tif
Skipping SUM file
CEN7\Cen7_AuroraB_CENPA\crop_rep3_left\SUM_rep3_image002_rep2-1.tif
Skipping SUM file
CEN7\Cen7_AuroraB_CENPA\crop_rep3_left\SUM_rep3_image003-1.tif
Skipping SUM file
CEN7\Cen7_AuroraB_CENPA\crop_rep3_left\SUM_rep3_image003_rep2-1.tif
Skipping SUM file
CEN7\Cen7_AuroraB_CENPA\crop_rep3_left\SUM_rep3_image003_rep2-2.tif
Skipping SUM file
CEN7\Cen7_AuroraB_CENPA\crop_rep3_left\SUM_rep3_image004_rep2-1.tif
Skipping SUM file
CEN7\Cen7_AuroraB_CENPA\crop_rep3_left\SUM_rep3_image005-1.tif
Skipping SUM file
CEN7\Cen7_AuroraB_CENPA\crop_rep3_left\SUM_rep3_image005-2.tif
Skipping SUM file
CEN7\Cen7_AuroraB_CENPA\crop_rep3_left\SUM_rep3_image005_rep2-1.tif
Skipping SUM file
CEN7\Cen7_AuroraB_CENPA\crop_rep3_left\SUM_rep3_image006-1.tif
Skipping SUM file
CEN7\Cen7_AuroraB_CENPA\crop_rep3_left\SUM_rep3_image006_rep2-1.tif
Skipping SUM file
CEN7\Cen7_AuroraB_CENPA\crop_rep3_left\SUM_rep3_image007_rep2-1.tif
Skipping SUM file
CEN7\Cen7_AuroraB_CENPA\crop_rep3_left\SUM_rep3_image008-1.tif
Skipping SUM file
CEN7\Cen7_AuroraB_CENPA\crop_rep3_left\SUM_rep3_image008_rep2-1.tif
Skipping SUM file
CEN7\Cen7_AuroraB_CENPA\crop_rep3_left\SUM_rep3_image009-1.tif
Skipping SUM file
CEN7\Cen7_AuroraB_CENPA\crop_rep3_left\SUM_rep3_image009_rep2-1.tif
Skipping SUM file
CEN7\Cen7_AuroraB_CENPA\crop_rep3_left\SUM_rep3_image010-1.tif
Skipping SUM file
CEN7\Cen7_AuroraB_CENPA\crop_rep3_left\SUM_rep3_image010_rep2-1.tif
Skipping SUM file
CEN7\Cen7_AuroraB_CENPA\crop_rep3_left\SUM_rep3_image011_rep2-1.tif
Skipping SUM file
CEN7\Cen7_AuroraB_CENPA\crop_rep3_left\SUM_rep3_image012_rep2-1.tif
Skipping SUM file
CEN7\Cen7_AuroraB_CENPA\crop_rep3_left\SUM_rep3_image013_rep2-1.tif
Skipping SUM file
CEN7\Cen7_CENPB_CENPA\crop_rep0\sead012-1-1.tif
(7, 4, 277, 149)
Bright peak distance 35.53500822691502 or dim peak distance 1.6435540942056952 exceeds max distance 20.
CEN7\Cen7_CENPB_CENPA\crop_rep0\spread001-1-1.tif
(7, 4, 174, 159)
Not enough peaks found in CEN7\Cen7_CENPB_CENPA\crop_rep0\spread001-1-1.tif. Skipping file.
CEN7\Cen7_CENPB_CENPA\crop_rep0\spread002-1-1.tif
(8, 4, 300, 220)
Not enough peaks found in CEN7\Cen7_CENPB_CENPA\crop_rep0\spread002-1-1.tif. Skipping file.
CEN7\Cen7_CENPB_CENPA\crop_rep0\spread003-1-1.tif
(7, 4, 206, 438)
Bright peak distance 3.4612570626168124 or dim peak distance 253.24424420354003 exceeds max distance 20.
CEN7\Cen7_CENPB_CENPA\crop_rep0\spread004-1-1.tif
(10, 4, 290, 289)
CEN7\Cen7_CENPB_CENPA\crop_rep0\spread005-1-1.tif
(11, 4, 213, 285)
CEN7\Cen7_CENPB_CENPA\crop_rep0\spread006-1-1.tif
(14, 4, 124, 220)
CEN7\Cen7_CENPB_CENPA\crop_rep0\spread006-2-1.tif
(14, 4, 216, 266)
CEN7\Cen7_CENPB_CENPA\crop_rep0\spread007-1.tif
(10, 4, 708, 849)
Bright peak distance 16.64468173207709 or dim peak distance 44.225073330760125 exceeds max distance 20.
CEN7\Cen7_CENPB_CENPA\crop_rep0\spread008-1-1.tif
(9, 4, 244, 111)
Not enough peaks found in CEN7\Cen7_CENPB_CENPA\crop_rep0\spread008-1-1.tif. Skipping file.
CEN7\Cen7_CENPB_CENPA\crop_rep0\spread009-1-1.tif
(9, 4, 330, 165)
Not enough peaks found in CEN7\Cen7_CENPB_CENPA\crop_rep0\spread009-1-1.tif. Skipping file.
CEN7\Cen7_CENPB_CENPA\crop_rep0\spread009-2-1.tif
(9, 4, 352, 241)
Not enough peaks found in CEN7\Cen7_CENPB_CENPA\crop_rep0\spread009-2-1.tif. Skipping file.
CEN7\Cen7_CENPB_CENPA\crop_rep0\spread011-1-1.tif
(10, 4, 112, 267)
CEN7\Cen7_CENPB_CENPA\crop_rep0\spread013-1-1.tif
(7, 4, 145, 163)
Not enough peaks found in CEN7\Cen7_CENPB_CENPA\crop_rep0\spread013-1-1.tif. Skipping file.
CEN7\Cen7_CENPB_CENPA\crop_rep0\spread013-2-1.tif
(7, 4, 253, 389)
Not enough peaks found in CEN7\Cen7_CENPB_CENPA\crop_rep0\spread013-2-1.tif. Skipping file.
CEN7\Cen7_CENPB_CENPA\crop_rep0\spread014-1.tif
(10, 4, 333, 270)
Bright peak distance 49.63081046022497 or dim peak distance 0.3442270978251743 exceeds max distance 20.
CEN7\Cen7_CENPB_CENPA\crop_rep0\spread014-2.tif
(10, 4, 510, 225)
CEN7\Cen7_CENPB_CENPA\crop_rep0\spread014-3.tif
(10, 4, 450, 423)
CEN7\Cen7_CENPB_CENPA\crop_rep0\spread015-1-1.tif
(11, 4, 327, 157)
Bright peak distance 16.460296413633973 or dim peak distance 42.51330513408146 exceeds max distance 20.
CEN7\Cen7_CENPB_CENPA\crop_rep0\spread015-2-1.tif
(11, 4, 180, 184)
CEN7\Cen7_CENPB_CENPA\crop_rep1\image002-1.tif
(18, 4, 478, 322)
CEN7\Cen7_CENPB_CENPA\crop_rep1\image003-1.tif
(18, 4, 250, 133)
CEN7\Cen7_CENPB_CENPA\crop_rep1\image003-2.tif
(18, 4, 276, 363)
Bright peak distance 27.86973745010853 or dim peak distance 18.216661039902156 exceeds max distance 20.
CEN7\Cen7_CENPB_CENPA\crop_rep1\image004-1.tif
(17, 4, 718, 817)
CEN7\Cen7_CENPB_CENPA\crop_rep1\image005-1.tif
(23, 4, 246, 319)
CEN7\Cen7_CENPB_CENPA\crop_rep1\image005-2.tif
(23, 4, 323, 407)
CEN7\Cen7_CENPB_CENPA\crop_rep1\image006-1.tif
(15, 4, 275, 402)
CEN7\Cen7_CENPB_CENPA\crop_rep1\image007-1-1.tif
(17, 4, 297, 196)
CEN7\Cen7_CENPB_CENPA\crop_rep1\image008-1.tif
(23, 4, 189, 190)
CEN7\Cen7_CENPB_CENPA\crop_rep1\image008-2.tif
(23, 4, 230, 311)
CEN7\Cen7_CENPB_CENPA\crop_rep1\image008-3.tif
(23, 4, 225, 138)
CEN7\Cen7_CENPB_CENPA\crop_rep1\image009-1.tif
(19, 4, 441, 558)
CEN7\Cen7_CENPB_CENPA\crop_rep1\image010-1.tif
(18, 4, 245, 220)
CEN7\Cen7_CENPB_CENPA\crop_rep1\image010-2.tif
(18, 4, 197, 243)
CEN7\Cen7_CENPB_CENPA\crop_rep1\image011-1.tif
(18, 4, 175, 228)
CEN7\Cen7_CENPB_CENPA\crop_rep1\image011-2.tif
(18, 4, 263, 176)
CEN7\Cen7_CENPB_CENPA\crop_rep1\image012-1.tif
(23, 4, 138, 290)
CEN7\Cen7_CENPB_CENPA\crop_rep1\image012-2.tif
(23, 4, 186, 165)
CEN7\Cen7_CENPB_CENPA\crop_rep1\image012-3.tif
(23, 4, 303, 195)
CEN7\Cen7_CENPB_CENPA\crop_rep1\image013-1.tif
(15, 4, 112, 324)
CEN7\Cen7_CENPB_CENPA\crop_rep1\image013-2.tif
(15, 4, 206, 340)
CEN7\Cen7_CENPB_CENPA\crop_rep2\image001-1.tif
(22, 4, 378, 225)
CEN7\Cen7_CENPB_CENPA\crop_rep2\image001-2.tif
(22, 4, 474, 384)
CEN7\Cen7_CENPB_CENPA\crop_rep2\image002-1.tif
(28, 4, 375, 1059)
CEN7\Cen7_CENPB_CENPA\crop_rep2\image004-1.tif
(19, 4, 714, 351)
CEN7\Cen7_CENPB_CENPA\crop_rep2\image005-1.tif
(22, 4, 366, 207)
CEN7\Cen7_CENPB_CENPA\crop_rep2\image006-1.tif
(17, 4, 366, 501)
CEN7\Cen7_CENPB_CENPA\crop_rep2\image007-1.tif
(19, 4, 215, 198)
CEN7\Cen7_CENPB_CENPA\crop_rep2\image008-1.tif
(17, 4, 484, 554)
Bright peak distance 4.367743394488857 or dim peak distance 96.74877068298096 exceeds max distance 20.
CEN7\Cen7_CENPB_CENPA\crop_rep2\image009-1.tif
(21, 4, 327, 261)
CEN7\Cen7_CENPB_CENPA\crop_rep2\image010-1.tif
(20, 4, 214, 765)
CEN7\Cen7_CENPB_CENPA\crop_rep2\image010-2.tif
(20, 4, 508, 268)
Bright peak distance 5.381322963419737 or dim peak distance 36.060216772124974 exceeds max distance 20.
CEN7\Cen7_CENPB_CENPA\crop_rep2\image010-3.tif
(20, 4, 187, 171)
Bright peak distance 36.18924288795502 or dim peak distance 23.24041940191296 exceeds max distance 20.
CEN7\Cen7_CENPB_CENPA\crop_rep3\image001-1.tif
(19, 4, 264, 174)
Bright peak distance 4.368266459598694 or dim peak distance 24.000808258505053 exceeds max distance 20.
CEN7\Cen7_CENPB_CENPA\crop_rep3\image001-2.tif
(19, 4, 441, 178)
CEN7\Cen7_CENPB_CENPA\crop_rep3\image002-1.tif
(15, 4, 204, 285)
CEN7\Cen7_CENPB_CENPA\crop_rep3\image002-2.tif
(15, 4, 405, 915)
CEN7\Cen7_CENPB_CENPA\crop_rep3\image003-1.tif
(12, 4, 898, 782)
Bright peak distance 4.809446969396075 or dim peak distance 45.60515824347173 exceeds max distance 20.
CEN7\Cen7_CENPB_CENPA\crop_rep3\image004-1.tif
(10, 4, 354, 918)
Bright peak distance 4.326958679929559 or dim peak distance 172.4220087820173 exceeds max distance 20.
CEN7\Cen7_CENPB_CENPA\crop_rep3\image005-1.tif
(12, 4, 339, 381)
CEN7\Cen7_CENPB_CENPA\crop_rep3\image006-1.tif
(15, 4, 786, 732)
CEN7\Cen7_CENPB_CENPA\crop_rep3\image007-1.tif
(16, 4, 768, 714)
CEN7\Cen7_CENPB_CENPA\crop_rep3\image008-1.tif
(16, 4, 273, 540)
CEN7\Cen7_CENPB_CENPA\crop_rep3\image008-2.tif
(16, 4, 194, 203)
CEN7\Cen7_CENPB_CENPA\crop_rep3\image009-1.tif
(13, 4, 438, 561)
CEN7\Cen7_CENPB_CENPA\crop_rep3\image010-1.tif
(11, 4, 468, 372)
CEN7\Cen7_CENPE_CENPA\crop_rep1\rep1_image001-1.tif
(31, 4, 509, 749)
CEN7\Cen7_CENPE_CENPA\crop_rep1\rep1_image002-1.tif
(50, 4, 492, 562)
CEN7\Cen7_CENPE_CENPA\crop_rep1\rep1_image003-1.tif
(31, 4, 600, 636)
CEN7\Cen7_CENPE_CENPA\crop_rep1\rep1_image004-1.tif
(30, 4, 1191, 831)
CEN7\Cen7_CENPE_CENPA\crop_rep1\rep1_image005-1.tif
(25, 4, 654, 687)
CEN7\Cen7_CENPE_CENPA\crop_rep1\rep1_image006-1.tif
(43, 4, 511, 591)
Bright peak distance 4.067552807823945 or dim peak distance 34.69255107640594 exceeds max distance 20.
CEN7\Cen7_CENPE_CENPA\crop_rep1\rep1_image007-1.tif
(38, 4, 435, 738)
CEN7\Cen7_CENPE_CENPA\crop_rep1\rep1_image008-1.tif
(44, 4, 448, 431)
CEN7\Cen7_CENPE_CENPA\crop_rep1\rep1_image008-2.tif
(44, 4, 618, 276)
CEN7\Cen7_CENPE_CENPA\crop_rep1\rep1_image009-1.tif
(27, 4, 435, 348)
Bright peak distance 3.724137931034477 or dim peak distance 53.293420972742 exceeds max distance 20.
CEN7\Cen7_CENPE_CENPA\crop_rep1\rep1_image009-2.tif
(27, 4, 468, 417)
CEN7\Cen7_CENPE_CENPA\crop_rep1\rep1_image010-1.tif
(30, 4, 482, 553)
CEN7\Cen7_CENPE_CENPA\crop_rep1\rep1_image012-1.tif
(35, 4, 660, 513)
CEN7\Cen7_CENPE_CENPA\crop_rep1\rep1_image014-1.tif
(53, 4, 619, 528)
CEN7\Cen7_CENPE_CENPA\crop_rep1\rep1_image015-1.tif
(31, 4, 549, 462)
CEN7\Cen7_CENPE_CENPA\crop_rep1\rep1_image016-1.tif
(31, 4, 822, 600)
Bright peak distance 43.34448267248191 or dim peak distance 0.22092728275595003 exceeds max distance 20.
CEN7\Cen7_CENPE_CENPA\crop_rep1\rep1_image018-1.tif
(34, 4, 766, 708)
CEN7\Cen7_CENPE_CENPA\crop_rep2\rep2_image006-1.tif
(35, 4, 278, 188)
CEN7\Cen7_CENPE_CENPA\crop_rep2\rep2_image007-1.tif
(55, 4, 398, 460)
Bright peak distance 26.13375295755842 or dim peak distance 1.4535563443370663 exceeds max distance 20.
CEN7\Cen7_CENPE_CENPA\crop_rep2\rep2_image008-1.tif
(34, 4, 543, 513)
CEN7\Cen7_CENPE_CENPA\crop_rep2\rep2_image009-1.tif
(49, 4, 335, 337)
CEN7\Cen7_CENPE_CENPA\crop_rep2\rep2_image010-1.tif
(42, 4, 436, 390)
CEN7\Cen7_CENPE_CENPA\crop_rep2\rep2_image011-1.tif
(39, 4, 450, 369)
CEN7\Cen7_CENPE_CENPA\crop_rep2\rep2_image012-1.tif
(44, 4, 329, 341)
CEN7\Cen7_CENPE_CENPA\crop_rep2\rep2_image014-1.tif
(46, 4, 334, 348)
CEN7\Cen7_CENPE_CENPA\crop_rep2\rep2_image015-1.tif
(51, 4, 369, 387)
CEN7\Cen7_CENPE_CENPA\crop_rep2\rep2_image015-2.tif
(51, 4, 609, 435)
CEN7\Cen7_CENPE_CENPA\crop_rep2\rep2_image016-1.tif
(34, 4, 537, 593)
Bright peak distance 38.05971962131438 or dim peak distance 1.3613772959682824 exceeds max distance 20.
CEN7\Cen7_CENPE_CENPA\crop_rep2\rep2_image016-2.tif
(34, 4, 654, 411)
CEN7\Cen7_CENPE_CENPA\crop_rep2\rep2_image017-1.tif
(40, 4, 593, 643)
Bright peak distance 2.02715314922947 or dim peak distance 24.348837204286845 exceeds max distance 20.
CEN7\Cen7_CENPE_CENPA\crop_rep2\rep2_image017-2.tif
(40, 4, 508, 763)
CEN7\Cen7_CENPE_CENPA\crop_rep2\rep2_image018-1.tif
(41, 4, 500, 600)
CEN7\Cen7_CENPE_CENPA\crop_rep2\rep2_image019-1.tif
(34, 4, 394, 556)
CEN7\Cen7_CENPE_CENPA\crop_rep2\rep2_image019-2.tif
(34, 4, 639, 474)
CEN7\Cen7_CENPE_CENPA\crop_rep3\rep3_image001-1.tif
(23, 4, 276, 438)
CEN7\Cen7_CENPE_CENPA\crop_rep3\rep3_image001-2.tif
(23, 4, 468, 462)
CEN7\Cen7_CENPE_CENPA\crop_rep3\rep3_image002-1.tif
(28, 4, 690, 753)
CEN7\Cen7_CENPE_CENPA\crop_rep3\rep3_image003-1.tif
(23, 4, 522, 592)
Bright peak distance 36.756786020905196 or dim peak distance 2.7727926171497734 exceeds max distance 20.
CEN7\Cen7_CENPE_CENPA\crop_rep3\rep3_image003-2.tif
(23, 4, 406, 460)
CEN7\Cen7_CENPE_CENPA\crop_rep3\rep3_image003-3.tif
(23, 4, 364, 700)
CEN7\Cen7_CENPE_CENPA\crop_rep3\rep3_image004-1.tif
(25, 4, 389, 266)
CEN7\Cen7_CENPE_CENPA\crop_rep3\rep3_image004-2.tif
(25, 4, 630, 528)
CEN7\Cen7_CENPE_CENPA\crop_rep3\rep3_image005-1.tif
(28, 4, 549, 344)
CEN7\Cen7_CENPE_CENPA\crop_rep3\rep3_image005-2.tif
(28, 4, 320, 272)
CEN7\Cen7_CENPE_CENPA\crop_rep3\rep3_image006-1.tif
(31, 4, 298, 332)
CEN7\Cen7_CENPE_CENPA\crop_rep3\rep3_image008-1.tif
(31, 4, 608, 438)
CEN7\Cen7_CENPE_CENPA\crop_rep3\rep3_image009-1.tif
(41, 4, 585, 618)
CEN7\Cen7_CENPE_CENPA\crop_rep3\rep3_image009-2.tif
(41, 4, 729, 636)
CEN7\Cen7_CENPE_CENPA\crop_rep3\rep3_image010-1.tif
(27, 4, 688, 744)
CEN7\Cen7_CENPE_CENPA\crop_rep3\rep3_image011-2.tif
(26, 4, 804, 609)
CEN7\Cen7_CENPE_CENPA\crop_rep3\rep3_image012-1.tif
(28, 4, 360, 561)
CEN7\Cen7_CENPE_CENPA\crop_rep3\rep3_image013-1.tif
(28, 4, 744, 681)
CEN7\Cen7_CENPE_CENPA\crop_rep3\rep3_image013-2.tif
(28, 4, 745, 816)
CEN7\Cen7_CENPE_CENPA\crop_rep3\rep3_image014-1.tif
(29, 4, 516, 468)
CEN7\Cen7_CENPE_CENPA\crop_rep3\rep3_image015-1.tif
(37, 4, 476, 286)
CEN7\Cen7_CENPE_CENPA\crop_rep3\rep3_image017-1.tif
(33, 4, 373, 216)
CEN7\Cen7_CENPE_CENPA\crop_rep3\rep3_image017-2.tif
(33, 4, 410, 260)
CEN7\Cen7_INCENP_CENPA\crop_rep2\rep2_trep1_image001-1.tif
(27, 4, 316, 748)
CEN7\Cen7_INCENP_CENPA\crop_rep2\rep2_trep1_image002-1.tif
(30, 4, 475, 316)
CEN7\Cen7_INCENP_CENPA\crop_rep2\rep2_trep1_image002-2.tif
(30, 4, 286, 444)
CEN7\Cen7_INCENP_CENPA\crop_rep2\rep2_trep1_image002-3.tif
(30, 4, 243, 593)
CEN7\Cen7_INCENP_CENPA\crop_rep2\rep2_trep1_image003-1.tif
(38, 4, 284, 354)
CEN7\Cen7_INCENP_CENPA\crop_rep2\rep2_trep1_image004-1.tif
(37, 4, 190, 250)
CEN7\Cen7_INCENP_CENPA\crop_rep2\rep2_trep1_image004-2.tif
(37, 4, 257, 287)
CEN7\Cen7_INCENP_CENPA\crop_rep2\rep2_trep1_image006-1.tif
(25, 4, 263, 274)
CEN7\Cen7_INCENP_CENPA\crop_rep2\rep2_trep1_image008-1.tif
(35, 4, 317, 321)
CEN7\Cen7_INCENP_CENPA\crop_rep2\rep2_trep1_image010-1.tif
(31, 4, 324, 378)
CEN7\Cen7_INCENP_CENPA\crop_rep2\rep2_trep1_image011-1.tif
(28, 4, 190, 270)
CEN7\Cen7_INCENP_CENPA\crop_rep2\rep2_trep1_image012-1.tif
(30, 4, 169, 250)
CEN7\Cen7_INCENP_CENPA\crop_rep5\rep5_2_image_0002-1.tif
(29, 4, 228, 396)
CEN7\Cen7_INCENP_CENPA\crop_rep5\rep5_2_image_0003-1.tif
(35, 4, 232, 342)
CEN7\Cen7_INCENP_CENPA\crop_rep5\rep5_2_image_0007-1.tif
(40, 4, 303, 307)
CEN7\Cen7_INCENP_CENPA\crop_rep5\rep5_2_image_0008-1.tif
(35, 4, 309, 260)
CEN7\Cen7_INCENP_CENPA\crop_rep5\rep5_2_image_0011-1.tif
(38, 4, 319, 280)
CEN7\Cen7_INCENP_CENPA\crop_rep5\rep5_2_image_0011-2.tif
(38, 4, 217, 378)
CEN7\Cen7_INCENP_CENPA\crop_rep5\rep5_2_image_0012-1.tif
(40, 4, 376, 230)
CEN7\Cen7_INCENP_CENPA\crop_rep5\rep5_2_image_0013-1.tif

# Analyze Data

In [20]:
df['State'] = 'Bright'
df.iloc[1::2, df.columns.get_loc('State')] = 'Dim'

In [21]:
df['folder'] = df['filename'].str.split('\\').str[1]
df['rep'] = df['filename'].str.split('\\').str[2]
df.groupby(['folder', 'rep']).agg({'label': 'count','slices':np.mean}).reset_index()

C:\Users\smc\AppData\Local\Temp\ipykernel_224\145448295.py:3: FutureWarning: The provided callable <function mean at 0x00000184FF1825C0> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  df.groupby(['folder', 'rep']).agg({'label': 'count','slices':np.mean}).reset_index()

                folder             rep  label     slices
0   Cen7_AuroraB_CENPA       crop_rep1     28  34.714286
1   Cen7_AuroraB_CENPA       crop_rep2     34  30.705882
2   Cen7_AuroraB_CENPA  crop_rep3_left     40  40.200000
3     Cen7_CENPB_CENPA       crop_rep0     16  11.250000
4     Cen7_CENPB_CENPA       crop_rep1     40  19.500000
5     Cen7_CENPB_CENPA       crop_rep2     18  21.111111
6     Cen7_CENPB_CENPA       crop_rep3     20  14.800000
7     Cen7_CENPE_CENPA       crop_rep1     28  35.928571
8     Cen7_CENPE_CENPA       crop_rep2     28  41.000000
9     Cen7_CENPE_CENPA       crop_rep3     44  29.045455
10   Cen7_INCENP_CENPA       crop_rep2     24  31.500000
11   Cen7_INCENP_CENPA       crop_rep5     32  37.250000
12   Cen7_INCENP_CENPA  crop_rep7_left     40  30.900000
13     Cen7_KNL1_CENPA       crop_rep1     14  22.142857
14     Cen7_KNL1_CENPA       crop_rep2     40  24.300000
15     Cen7_KNL1_CENPA       crop_rep3     42  17.428571
16    Cen7_NDC80_CENPA       crop_rep1     24  25.833333
17    Cen7_NDC80_CENPA       crop_rep2     14  23.142857
18    Cen7_NDC80_CENPA  crop_rep3_left     22  30.363636
19      Cen7_SGO_CENPA       crop_rep1     20  17.900000
20      Cen7_SGO_CENPA       crop_rep2     16  19.625000
21      Cen7_SGO_CENPA       crop_rep3     18  19.333333
22  Cen7_TopoIIA_CENPA       crop_rep1     58  33.620690
23  Cen7_TopoIIA_CENPA       crop_rep2     22  47.272727
24  Cen7_TopoIIA_CENPA       crop_rep3     22  43.363636

In [22]:
bright_df = df[df['State'] == 'Bright']
dim_df = df[df['State'] == 'Dim']

combined_df = bright_df.merge(dim_df, on=['filename', 'folder', ], suffixes=('_bright', '_dim'))
combined_df['FISH_ratio']= combined_df['FISH_total_intensity_bright'] / combined_df['FISH_total_intensity_dim']
combined_df['c0_ratio'] = combined_df['total_intensity_bright'] / combined_df['total_intensity_dim']
combined_df['c1_ratio'] = combined_df['total_intensity_c1_bright'] / combined_df['total_intensity_c1_dim']
combined_df['c2_ratio'] = combined_df['total_intensity_c2_bright'] / combined_df['total_intensity_c2_dim']
combined_df['c3_ratio'] = combined_df['total_intensity_c3_bright'] / combined_df['total_intensity_c3_dim']

combined_df['FISH_ratio_i'] = 1 / combined_df['FISH_ratio']
combined_df['c0_ratio_i'] = 1 / combined_df['c0_ratio']
combined_df['c1_ratio_i'] = 1 / combined_df['c1_ratio']
combined_df['c2_ratio_i'] = 1 / combined_df['c2_ratio']
combined_df['c3_ratio_i'] = 1 / combined_df['c3_ratio']
combined_df

,label_bright,centroid-0_bright,centroid-1_bright,area_bright,mean_intensity_bright,total_intensity_bright,mean_intensity_c1_bright,total_intensity_c1_bright,mean_intensity_c2_bright,total_intensity_c2_bright,...,FISH_ratio,c0_ratio,c1_ratio,c2_ratio,c3_ratio,FISH_ratio_i,c0_ratio_i,c1_ratio_i,c2_ratio_i,c3_ratio_i
0,1.0,324.0,89.5,502.0,511.617523,256831.996643,480.519928,241221.003845,5957.073730,2.990451e+06,...,1.499137,1.422080,1.239204,1.186483,1.454172,0.667051,0.703195,0.806970,0.842827,0.687677
1,1.0,75.0,158.5,484.0,1557.593018,753875.020508,789.109497,381928.996582,21882.462891,1.059111e+07,...,2.359160,1.537482,1.549879,2.243623,2.057317,0.423880,0.650414,0.645212,0.445708,0.486070
2,1.0,59.5,58.0,436.0,2013.575684,877918.998047,786.371582,342858.009766,7039.536621,3.069238e+06,...,2.792112,2.057211,1.262564,1.181580,0.994089,0.358152,0.486095,0.792039,0.846325,1.005947
3,1.0,66.0,87.5,426.0,1720.739380,733034.975830,710.589172,302710.987427,13419.406250,5.716667e+06,...,2.359123,1.836177,1.017588,0.768440,1.531633,0.423886,0.544610,0.982716,1.301338,0.652898
4,1.0,398.0,100.0,355.0,1443.949341,512602.015991,492.380280,174794.999237,4190.126953,1.487495e+06,...,2.371269,1.659180,0.701672,1.046452,1.378087,0.421715,0.602707,1.425167,0.955610,0.725644
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
347,1.0,942.5,262.0,506.0,1836.120605,929077.026367,486.393280,246114.999695,4108.541504,2.078922e+06,...,1.585129,1.439722,0.867411,0.706706,0.499809,0.630863,0.694579,1.152855,1.415017,2.000765
348,1.0,369.0,309.0,517.0,1146.889771,592942.011353,645.079285,333505.990173,5935.404297,3.068604e+06,...,1.605485,1.253275,1.067025,0.738341,0.537941,0.622865,0.797909,0.937186,1.354388,1.858941
349,1.0,162.5,297.0,326.0,566.717773,184749.994141,731.404907,238437.999756,5833.717773,1.901792e+06,...,1.587022,0.733298,1.109633,2.072186,1.366198,0.630111,1.363702,0.901199,0.482582,0.731959
350,1.0,213.0,302.0,469.0,1688.545898,791928.026367,536.729187,251725.988708,4483.110840,2.102579e+06,...,2.596470,2.234062,0.852294,1.086778,0.976730,0.385138,0.447615,1.173304,0.920151,1.023825
351,1.0,590.5,372.0,530.0,1124.418823,595941.976318,775.458496,410993.002930,3814.935791,2.021916e+06,...,3.840560,2.599461,1.172189,1.606174,1.731409,0.260379,0.384695,0.853105,0.622598,0.577564

In [23]:
# Make interactive plot for examining FISH signal ratios

f=go.FigureWidget(
    #px.box(df, x='folder', color='State', y='total_intensity_c3', points='all', hover_data=['filename'])
    px.box(combined_df, x='folder', y='FISH_ratio_i', points='all', hover_data=['filename'], range_y=[0,2], width=1400, height=800)
    )

def click_fn(trace, points, state):
    
    if (len(points.point_inds)>0):
        idx = f.data[points.trace_index]['customdata'][points.point_inds[-1]][0]
        print(idx)
        viewer.layers.clear()
        process_file(idx, viewer=viewer, display=True)

for a in f.data:
    a.on_click(click_fn)
f.write_html('FISH_signal_ratio.html')
f

FigureWidget({
    'data': [{'alignmentgroup': 'True',
              'boxpoints': 'all',
              'customdata': array([['CEN7\\Cen7_AuroraB_CENPA\\crop_rep1\\rep1_image001-1.tif'],
                                   ['CEN7\\Cen7_AuroraB_CENPA\\crop_rep1\\rep1_image003-1.tif'],
                                   ['CEN7\\Cen7_AuroraB_CENPA\\crop_rep1\\rep1_image003-2.tif'],
                                   ...,
                                   ['CEN7\\Cen7_TopoIIA_CENPA\\crop_rep3\\Image015-1.tif'],
                                   ['CEN7\\Cen7_TopoIIA_CENPA\\crop_rep3\\Image016-1.tif'],
                                   ['CEN7\\Cen7_TopoIIA_CENPA\\crop_rep3\\Image017-1.tif']], dtype=object),
              'hovertemplate': 'folder=%{x}<br>FISH_ratio_i=%{y}<br>filename=%{customdata[0]}<extra></extra>',
              'legendgroup': '',
              'marker': {'color': '#636efa'},
              'name': '',
              'notched': False,
              'offsetgroup': '',
              'orientation': 'v',
              'showlegend': False,
              'type': 'box',
              'uid': 'a9fd70dc-570f-4964-82b3-870a59e2e5e0',
              'x': array(['Cen7_AuroraB_CENPA', 'Cen7_AuroraB_CENPA', 'Cen7_AuroraB_CENPA', ...,
                          'Cen7_TopoIIA_CENPA', 'Cen7_TopoIIA_CENPA', 'Cen7_TopoIIA_CENPA'],
                         dtype=object),
              'x0': ' ',
              'xaxis': 'x',
              'y': {'bdata': ('TgLfTnpY5T8XxaZ02CDbPx6CFob169' ... '5g3inkPyvurEUbptg/1oK/XAuq0D8='),
                    'dtype': 'f8'},
              'y0': ' ',
              'yaxis': 'y'}],
    'layout': {'boxmode': 'group',
               'height': 800,
               'legend': {'tracegroupgap': 0},
               'margin': {'t': 60},
               'template': '...',
               'width': 1400,
               'xaxis': {'anchor': 'y', 'domain': [0.0, 1.0], 'title': {'text': 'folder'}},
               'yaxis': {'anchor': 'x', 'domain': [0.0, 1.0], 'range': [0, 2], 'title': {'text': 'FISH_ratio_i'}}}
})

In [24]:
# Make interactive plot for examining CenpA signal ratios

f=go.FigureWidget(
    #px.box(df, x='folder', color='State', y='total_intensity_c3', points='all', hover_data=['filename'])
    px.box(combined_df, x='folder', y='c1_ratio_i', points='all', hover_data=['filename'], range_y=[0,2])
    )

def click_fn(trace, points, state):
    
    if (len(points.point_inds)>0):
        idx = f.data[points.trace_index]['customdata'][points.point_inds[-1]][0]
        print(idx)
        viewer.layers.clear()
        process_file(idx, viewer=viewer, display=True)

for a in f.data:
    a.on_click(click_fn)
f.write_html('cenpA_signal_ratio.html')
f

FigureWidget({
    'data': [{'alignmentgroup': 'True',
              'boxpoints': 'all',
              'customdata': array([['CEN7\\Cen7_AuroraB_CENPA\\crop_rep1\\rep1_image001-1.tif'],
                                   ['CEN7\\Cen7_AuroraB_CENPA\\crop_rep1\\rep1_image003-1.tif'],
                                   ['CEN7\\Cen7_AuroraB_CENPA\\crop_rep1\\rep1_image003-2.tif'],
                                   ...,
                                   ['CEN7\\Cen7_TopoIIA_CENPA\\crop_rep3\\Image015-1.tif'],
                                   ['CEN7\\Cen7_TopoIIA_CENPA\\crop_rep3\\Image016-1.tif'],
                                   ['CEN7\\Cen7_TopoIIA_CENPA\\crop_rep3\\Image017-1.tif']], dtype=object),
              'hovertemplate': 'folder=%{x}<br>c1_ratio_i=%{y}<br>filename=%{customdata[0]}<extra></extra>',
              'legendgroup': '',
              'marker': {'color': '#636efa'},
              'name': '',
              'notched': False,
              'offsetgroup': '',
              'orientation': 'v',
              'showlegend': False,
              'type': 'box',
              'uid': '3c9fc52c-a6de-48da-89ac-67e1e28a5f65',
              'x': array(['Cen7_AuroraB_CENPA', 'Cen7_AuroraB_CENPA', 'Cen7_AuroraB_CENPA', ...,
                          'Cen7_TopoIIA_CENPA', 'Cen7_TopoIIA_CENPA', 'Cen7_TopoIIA_CENPA'],
                         dtype=object),
              'x0': ' ',
              'xaxis': 'x',
              'y': {'bdata': ('7u96xbHS6T8/lau+kqXkP+rK+LJiWO' ... 'OGntbsPzhEcP/ZxfI/dNZB5KFM6z8='),
                    'dtype': 'f8'},
              'y0': ' ',
              'yaxis': 'y'}],
    'layout': {'boxmode': 'group',
               'legend': {'tracegroupgap': 0},
               'margin': {'t': 60},
               'template': '...',
               'xaxis': {'anchor': 'y', 'domain': [0.0, 1.0], 'title': {'text': 'folder'}},
               'yaxis': {'anchor': 'x', 'domain': [0.0, 1.0], 'range': [0, 2], 'title': {'text': 'c1_ratio_i'}}}
})

In [25]:
# Make interactive plot for examining kinteochore protein signal ratios
f=go.FigureWidget(
    px.box(combined_df, x='folder', y='c2_ratio_i', points='all', hover_data=['filename'], range_y=[0,2], height=800)
    )

def click_fn(trace, points, state):
    
    if (len(points.point_inds)>0):
        idx = f.data[points.trace_index]['customdata'][points.point_inds[-1]][0]
        print(idx)
        process_file(idx, viewer=viewer, display=True)
        for layer in viewer.layers:
            layer.visible = False
        viewer.layers[-1].visible = True
        viewer.layers[-4].visible = True
        viewer.layers[-5].visible = True
        viewer.layers[-6].visible = True
        viewer.layers[-1].name = idx

for a in f.data:
    a.on_click(click_fn)
f.write_html('core_protein_signal_ratio.html')
f

FigureWidget({
    'data': [{'alignmentgroup': 'True',
              'boxpoints': 'all',
              'customdata': array([['CEN7\\Cen7_AuroraB_CENPA\\crop_rep1\\rep1_image001-1.tif'],
                                   ['CEN7\\Cen7_AuroraB_CENPA\\crop_rep1\\rep1_image003-1.tif'],
                                   ['CEN7\\Cen7_AuroraB_CENPA\\crop_rep1\\rep1_image003-2.tif'],
                                   ...,
                                   ['CEN7\\Cen7_TopoIIA_CENPA\\crop_rep3\\Image015-1.tif'],
                                   ['CEN7\\Cen7_TopoIIA_CENPA\\crop_rep3\\Image016-1.tif'],
                                   ['CEN7\\Cen7_TopoIIA_CENPA\\crop_rep3\\Image017-1.tif']], dtype=object),
              'hovertemplate': 'folder=%{x}<br>c2_ratio_i=%{y}<br>filename=%{customdata[0]}<extra></extra>',
              'legendgroup': '',
              'marker': {'color': '#636efa'},
              'name': '',
              'notched': False,
              'offsetgroup': '',
              'orientation': 'v',
              'showlegend': False,
              'type': 'box',
              'uid': '07fa057f-46da-4056-b01e-6f2ed8ce070a',
              'x': array(['Cen7_AuroraB_CENPA', 'Cen7_AuroraB_CENPA', 'Cen7_AuroraB_CENPA', ...,
                          'Cen7_TopoIIA_CENPA', 'Cen7_TopoIIA_CENPA', 'Cen7_TopoIIA_CENPA'],
                         dtype=object),
              'x0': ' ',
              'xaxis': 'x',
              'y': {'bdata': ('ITmOyG/46j/kHZzjeYbcP9dUh54XFe' ... '6YoOLeP3Y1Z13hce0/mj9c0lHs4z8='),
                    'dtype': 'f8'},
              'y0': ' ',
              'yaxis': 'y'}],
    'layout': {'boxmode': 'group',
               'height': 800,
               'legend': {'tracegroupgap': 0},
               'margin': {'t': 60},
               'template': '...',
               'xaxis': {'anchor': 'y', 'domain': [0.0, 1.0], 'title': {'text': 'folder'}},
               'yaxis': {'anchor': 'x', 'domain': [0.0, 1.0], 'range': [0, 2], 'title': {'text': 'c2_ratio_i'}}}
})

In [26]:
df.groupby(['folder']).agg({'label':'size', 'filename':lambda x: len(np.unique(x))}).reset_index()

               folder  label  filename
0  Cen7_AuroraB_CENPA    102        51
1    Cen7_CENPB_CENPA     94        47
2    Cen7_CENPE_CENPA    100        50
3   Cen7_INCENP_CENPA     96        48
4     Cen7_KNL1_CENPA     96        48
5    Cen7_NDC80_CENPA     60        30
6      Cen7_SGO_CENPA     54        27
7  Cen7_TopoIIA_CENPA    102        51

In [27]:
combined_df.to_csv('combined_peak_datav3.csv')